services:
  mysql-db:
    image: mysql:8.0
    container_name: sqa-mysql-local
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 20

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: sqa-phpmyadmin-local
    environment:
      PMA_HOST: mysql-db
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8080:80"
    depends_on:
      mysql-db:
        condition: service_healthy

volumes:
  mysql_data:
